# Added YARN orb for deployment
orbs: 
  node: circleci/node@5.0.2

version: 2.1

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn
      - add_ssh_keys:
          fingerprints:
            - "71:fa:d5:3f:b2:f5:bd:be:cc:16:68:f9:8c:34:d5:81"
      - run: git config user.email "bayarjargal.jr@gmail.com"
      - run: git config user.name "Bayarjargal.J"
      - run: yarn run deploy
      
workflows:
  install:
    jobs:
      - install